// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models.data;

#nullable disable

namespace Models.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507024157_AddPasswordToUtilisateur")]
    partial class AddPasswordToUtilisateur
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Communication_VertLavenir.Models.adresse", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("NumApt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomRue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numAdresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Adresses");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nomRue = "Rue du Stade",
                            numAdresse = "1"
                        },
                        new
                        {
                            id = 2,
                            NumApt = "A",
                            nomRue = "Avenue des Fleurs",
                            numAdresse = "2"
                        },
                        new
                        {
                            id = 3,
                            nomRue = "Boulevard Central",
                            numAdresse = "3"
                        },
                        new
                        {
                            id = 4,
                            NumApt = "12B",
                            nomRue = "Rue Sainte",
                            numAdresse = "4"
                        },
                        new
                        {
                            id = 5,
                            nomRue = "Rue des Rosiers",
                            numAdresse = "5"
                        },
                        new
                        {
                            id = 6,
                            nomRue = "Place de la République",
                            numAdresse = "6"
                        });
                });

            modelBuilder.Entity("Communication_VertLavenir.Models.evenement", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Evenements");
                });

            modelBuilder.Entity("Communication_VertLavenir.Models.paiement", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.Property<int>("montant")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("Communication_VertLavenir.Models.utilisateur", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("AddressId");

                    b.ToTable("Utilisateurs");

                    b.HasData(
                        new
                        {
                            id = 1,
                            AddressId = 1,
                            email = "alice.dupont@example.com",
                            nom = "Dupont",
                            numero = "0600000001",
                            password = "Pass123!",
                            prenom = "Alice",
                            role = "chefBenevol"
                        },
                        new
                        {
                            id = 2,
                            AddressId = 2,
                            email = "bob.martin@example.com",
                            nom = "Martin",
                            numero = "0600000002",
                            password = "Pass123!",
                            prenom = "Bob",
                            role = "benevol"
                        },
                        new
                        {
                            id = 3,
                            AddressId = 3,
                            email = "claire.leroy@example.com",
                            nom = "Leroy",
                            numero = "0600000003",
                            password = "Pass123!",
                            prenom = "Claire",
                            role = "donneur"
                        },
                        new
                        {
                            id = 4,
                            AddressId = 4,
                            email = "david.petit@example.com",
                            nom = "Petit",
                            numero = "0600000004",
                            password = "Pass123!",
                            prenom = "David",
                            role = "utilisateur"
                        },
                        new
                        {
                            id = 5,
                            AddressId = 5,
                            email = "emma.moreau@example.com",
                            nom = "Moreau",
                            numero = "0600000005",
                            password = "Pass123!",
                            prenom = "Emma",
                            role = "chefBenevol"
                        },
                        new
                        {
                            id = 6,
                            AddressId = 6,
                            email = "admin@example.com",
                            nom = "Admin",
                            numero = "0600000000",
                            password = "AdminPass!23",
                            prenom = "Super",
                            role = "admin"
                        });
                });

            modelBuilder.Entity("Communication_VertLavenir.Models.paiement", b =>
                {
                    b.HasOne("Communication_VertLavenir.Models.utilisateur", "utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("utilisateur");
                });

            modelBuilder.Entity("Communication_VertLavenir.Models.utilisateur", b =>
                {
                    b.HasOne("Communication_VertLavenir.Models.adresse", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
